apiVersion: v1
kind: Service
metadata:
  name: web-expose-service
spec:
  type: NodePort
  selector:
    app: concourse-web
  ports:
  - protocol: TCP
    name: "concourse-web-expose"
    port: 8080
    targetPort: 8080
  externalIPs:
  - 127.0.0.1
