apiVersion: v1
kind: Service
metadata:
  name: concourse-web-service
spec:
  selector:
    app: concourse-web
  ports:
  - protocol: TCP
    name: "concourse-web"
    port: 8080
    targetPort: 8080
  - protocol: TCP
    name: "concourse-worker"
    port: 2222
    targetPort: 2222
