apiVersion: v1
kind: Service
metadata:
  name: concourse-worker-service
spec:
  selector:
    app: concourse-worker
  ports:
  - protocol: TCP
    name: "concourse-worker-garden"
    port: 7777
    targetPort: 7777
  - protocol: TCP
    name: "concourse-worker-baggageclaim"
    port: 7788
    targetPort: 7788
  - protocol: TCP
    name: "concourse-worker-reaper"
    port: 7799
    targetPort: 7799
