apiVersion: v1
kind: Service
metadata:
  name: concourse-db-service
spec:
  selector:
    app: concourse-db
  ports:
  - protocol: TCP
    name: "concourse-postgres"
    port: 5432
    targetPort: 5432
