apiVersion: v1
kind: Secret
metadata:
  name: concourse-secret
type: Opaque
data:
  github.client.id: {{some base64 string}}
  github.client.secret: {{some base64 string}}
  github.username: {{some base64 string}}
  database.name: {{some base64 string}}
  database.user: {{some base64 string}}
  database.password: {{some base64 string}}
